name: magni-description-snap
base: core22
version: '1.1'
summary: Magni Description Snap
description: |
  Snap for Magni robot description and launch files.

grade: devel
confinement: devmode

parts:
  magni-description:
    plugin: colcon
    source: .
    build-packages:
      - python3-pip
      - python3-colcon-common-extensions

apps:
  description-launch:
    command: ros2 launch magni_description description.launch.py
    extensions: [ros2-humble]
